/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 80033
 Source Host           : localhost:3306
 Source Schema         : test-ai

 Target Server Type    : MySQL
 Target Server Version : 80033
 File Encoding         : 65001

 Date: 11/03/2025 17:50:00
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for workflows
-- ----------------------------
DROP TABLE IF EXISTS `workflows`;
CREATE TABLE `workflows`  (
  `id` int(0) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `app_id` int(0) NULL DEFAULT NULL,
  `graph` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 8 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of workflows
-- ----------------------------
INSERT INTO `workflows` VALUES (1, '测试模型', 1, '{\"nodes\":[{\"id\":\"2\",\"type\":\"llmNode\",\"data\":{\"title\":\"大模型\",\"description\":\"处理大模型相关问题\",\"expand\":true,\"outputDefs\":[{\"id\":\"pyiig8ntGWZhVdVz\",\"dataType\":\"Object\",\"name\":\"param\",\"children\":[{\"id\":\"1\",\"name\":\"newParam1\",\"dataType\":\"String\"},{\"id\":\"2\",\"name\":\"newParam2\",\"dataType\":\"String\"}]}]},\"position\":{\"x\":550,\"y\":50},\"measured\":{\"width\":355,\"height\":687},\"selected\":false},{\"id\":\"3\",\"type\":\"startNode\",\"data\":{\"title\":\"开始节点\",\"description\":\"开始定义输入参数\",\"expand\":true},\"position\":{\"x\":115,\"y\":50},\"measured\":{\"width\":306,\"height\":200},\"selected\":false,\"dragging\":false},{\"id\":\"4\",\"type\":\"endNode\",\"data\":{\"title\":\"结束节点\",\"description\":\"结束定义输出参数\",\"expand\":true},\"position\":{\"x\":1156,\"y\":48},\"measured\":{\"width\":306,\"height\":200},\"selected\":true,\"dragging\":false}],\"viewport\":{\"x\":250,\"y\":100,\"zoom\":1},\"edges\":[{\"markerEnd\":{\"type\":\"arrowclosed\",\"width\":20,\"height\":20},\"source\":\"3\",\"target\":\"2\",\"id\":\"xy-edge__3-2\",\"selected\":false},{\"markerEnd\":{\"type\":\"arrowclosed\",\"width\":20,\"height\":20},\"source\":\"2\",\"target\":\"4\",\"id\":\"xy-edge__2-4\",\"selected\":false}]}');
INSERT INTO `workflows` VALUES (2, 'test', 1, '{\"nodes\":[{\"id\":\"node_rovJujZGFnxF6rrM\",\"position\":{\"x\":80,\"y\":34},\"data\":{\"title\":\"开始节点\",\"description\":\"开始定义输入参数\"},\"type\":\"startNode\",\"selected\":false,\"measured\":{\"width\":306,\"height\":126}},{\"id\":\"node_YLO7yeEzpC25M3RG\",\"position\":{\"x\":919,\"y\":17},\"data\":{\"title\":\"结束节点\",\"description\":\"结束定义输出参数\"},\"type\":\"endNode\",\"selected\":false,\"measured\":{\"width\":306,\"height\":126}},{\"id\":\"node_fQPb4qDBl4VjcCMW\",\"position\":{\"x\":509,\"y\":32},\"data\":{\"title\":\"搜索引擎\",\"description\":\"通过搜索引擎搜索内容\",\"outputDefs\":[{\"name\":\"documents\",\"dataType\":\"Array\",\"nameDisabled\":true,\"dataTypeDisabled\":true,\"addChildDisabled\":true,\"children\":[{\"name\":\"title\",\"dataType\":\"String\",\"nameDisabled\":true,\"dataTypeDisabled\":true,\"id\":\"IF141xtLDoOg6uH8\"},{\"name\":\"content\",\"dataType\":\"String\",\"nameDisabled\":true,\"dataTypeDisabled\":true,\"id\":\"DGxm7RFOq2R8cyF6\"},{\"name\":\"documentId\",\"dataType\":\"Number\",\"nameDisabled\":true,\"dataTypeDisabled\":true,\"id\":\"1ZETL84STnkJeMPi\"},{\"name\":\"knowledgeId\",\"dataType\":\"Number\",\"nameDisabled\":true,\"dataTypeDisabled\":true,\"id\":\"E4OqcLEjtvDk76Hk\"}],\"id\":\"LEdA0XTx5bHrEaMf\"}]},\"type\":\"searchEngineNode\",\"selected\":false,\"measured\":{\"width\":306,\"height\":126},\"dragging\":false}],\"edges\":[],\"viewport\":{\"x\":250,\"y\":100,\"zoom\":1}}');
INSERT INTO `workflows` VALUES (3, '测试输出', 1, '{\"nodes\":[{\"id\":\"node_82BjuWLD2POIHUF2\",\"position\":{\"x\":29,\"y\":174},\"data\":{\"title\":\"开始节点\",\"description\":\"开始定义输入参数\",\"expand\":true,\"parameters\":[{\"id\":\"g3qfdWpJAsAiHoZx\",\"name\":\"test\",\"required\":true},{\"id\":\"4yGuWCCRLSR7IU9o\",\"name\":\"a\",\"required\":true}]},\"type\":\"startNode\",\"selected\":false,\"measured\":{\"width\":306,\"height\":241},\"dragging\":false},{\"id\":\"node_XUwEBFWaJT6inhm3\",\"position\":{\"x\":513,\"y\":176},\"data\":{\"title\":\"结束节点\",\"description\":\"结束定义输出参数\",\"expand\":true,\"outputDefs\":[{\"id\":\"CNZ8dn2u62EqAGGP\",\"ref\":\"node_82BjuWLD2POIHUF2.test\",\"name\":\"test\"},{\"id\":\"PC2L4oNEerMxKHMx\",\"name\":\"aa\",\"ref\":\"node_82BjuWLD2POIHUF2.a\"}]},\"type\":\"endNode\",\"selected\":false,\"measured\":{\"width\":347,\"height\":241},\"dragging\":false}],\"edges\":[{\"markerEnd\":{\"type\":\"arrowclosed\",\"width\":20,\"height\":20},\"source\":\"node_82BjuWLD2POIHUF2\",\"target\":\"node_XUwEBFWaJT6inhm3\",\"id\":\"xy-edge__node_82BjuWLD2POIHUF2-node_XUwEBFWaJT6inhm3\",\"selected\":false}],\"viewport\":{\"x\":250,\"y\":100,\"zoom\":1}}');
INSERT INTO `workflows` VALUES (7, 'test111', 1, '{\"nodes\":[{\"id\":\"node_yt0FdnTZcpx08fkg\",\"position\":{\"x\":-139,\"y\":104},\"data\":{\"title\":\"开始节点\",\"description\":\"开始定义输入参数\",\"expand\":true,\"parameters\":[{\"id\":\"qbYVQuFK8345rBl0\",\"name\":\"arr\",\"dataType\":\"Array\",\"required\":true}]},\"type\":\"startNode\",\"selected\":false,\"measured\":{\"width\":306,\"height\":209},\"dragging\":false},{\"id\":\"node_W0GdwxOZECvn4IiN\",\"position\":{\"x\":358,\"y\":105},\"data\":{\"title\":\"动态代码\",\"description\":\"动态执行代码\",\"expand\":true,\"engine\":\"groovy\",\"outputDefs\":[{\"id\":\"FBLNSiKI4PTNXuyn\",\"dataType\":\"Array\",\"name\":\"res\"}],\"parameters\":[{\"id\":\"u7tW4zSGrz1pfQnE\",\"name\":\"rows\",\"ref\":\"node_yt0FdnTZcpx08fkg.arr\"}],\"code\":\"// 获取最大列数\\n    def maxColumns = rows*.size().max()\\n    \\n    // 创建一个新的列表存储列数据\\n    def columns = (0..<maxColumns).collect { idx ->\\n        rows.collect { it[idx] }\\n    }\\n    \\n    return columns\"},\"type\":\"codeNode\",\"selected\":false,\"measured\":{\"width\":340,\"height\":589},\"dragging\":false},{\"id\":\"node_MYOX6bPCuYOlkkbm\",\"position\":{\"x\":788.789291416276,\"y\":105.7264251502344},\"data\":{\"title\":\"结束节点\",\"description\":\"结束定义输出参数\",\"expand\":true,\"outputDefs\":[{\"id\":\"9VvoSIplMZGBN3e6\",\"name\":\"输出\",\"ref\":\"node_W0GdwxOZECvn4IiN.res\"}]},\"type\":\"endNode\",\"selected\":true,\"measured\":{\"width\":342,\"height\":209},\"dragging\":false}],\"edges\":[{\"markerEnd\":{\"type\":\"arrowclosed\",\"width\":20,\"height\":20},\"source\":\"node_yt0FdnTZcpx08fkg\",\"target\":\"node_W0GdwxOZECvn4IiN\",\"id\":\"xy-edge__node_yt0FdnTZcpx08fkg-node_W0GdwxOZECvn4IiN\",\"selected\":false},{\"markerEnd\":{\"type\":\"arrowclosed\",\"width\":20,\"height\":20},\"source\":\"node_W0GdwxOZECvn4IiN\",\"target\":\"node_MYOX6bPCuYOlkkbm\",\"id\":\"xy-edge__node_W0GdwxOZECvn4IiN-node_MYOX6bPCuYOlkkbm\",\"selected\":false}],\"viewport\":{\"x\":474.67384867114697,\"y\":91.46615240660833,\"zoom\":1.3195079107728944}}');
INSERT INTO `workflows` VALUES (8, '测试保存', 1, '{\"nodes\":[{\"id\":\"node_q294Rop7Y5Mn7kVS\",\"position\":{\"x\":-67,\"y\":30},\"data\":{\"title\":\"开始节点\",\"description\":\"开始定义输入参数\"},\"type\":\"startNode\",\"selected\":false,\"measured\":{\"width\":306,\"height\":126}},{\"id\":\"node_ljPC7bL85VsDR5GM\",\"position\":{\"x\":520,\"y\":59},\"data\":{\"title\":\"循环\",\"description\":\"用于循环执行任务\"},\"type\":\"loopNode\",\"selected\":false,\"measured\":{\"width\":306,\"height\":126},\"dragging\":false},{\"id\":\"node_6NkeJWpoAiVEeSfT\",\"position\":{\"x\":884,\"y\":64},\"data\":{\"title\":\"大模型\",\"description\":\"使用大模型处理问题\"},\"type\":\"llmNode\",\"selected\":false,\"measured\":{\"width\":306,\"height\":126},\"dragging\":false},{\"id\":\"node_Mu2UKDuvV3bKp8lL\",\"position\":{\"x\":1288,\"y\":256},\"data\":{\"title\":\"知识库\",\"description\":\"通过知识库获取内容\",\"outputDefs\":[{\"name\":\"documents\",\"dataType\":\"Array\",\"nameDisabled\":true,\"dataTypeDisabled\":true,\"addChildDisabled\":true,\"children\":[{\"name\":\"title\",\"dataType\":\"String\",\"nameDisabled\":true,\"dataTypeDisabled\":true,\"id\":\"AOZBWOsAeNCMWhWO\"},{\"name\":\"content\",\"dataType\":\"String\",\"nameDisabled\":true,\"dataTypeDisabled\":true,\"id\":\"XuqdUHlSy9m5JyaJ\"},{\"name\":\"documentId\",\"dataType\":\"Number\",\"nameDisabled\":true,\"dataTypeDisabled\":true,\"id\":\"hNtTHi5YI2IVnu3n\"},{\"name\":\"knowledgeId\",\"dataType\":\"Number\",\"nameDisabled\":true,\"dataTypeDisabled\":true,\"id\":\"1VnKZuMe8hKCpkGW\"}],\"id\":\"Q7ODTl3f9X2vGdH0\"}]},\"type\":\"knowledgeNode\",\"selected\":false,\"measured\":{\"width\":306,\"height\":126},\"dragging\":false},{\"id\":\"node_CzPf0au4aE3naghj\",\"position\":{\"x\":1426,\"y\":603},\"data\":{\"title\":\"结束节点\",\"description\":\"结束定义输出参数\"},\"type\":\"endNode\",\"selected\":true,\"measured\":{\"width\":306,\"height\":126},\"dragging\":false}],\"edges\":[{\"markerEnd\":{\"type\":\"arrowclosed\",\"width\":20,\"height\":20},\"source\":\"node_q294Rop7Y5Mn7kVS\",\"target\":\"node_ljPC7bL85VsDR5GM\",\"id\":\"xy-edge__node_q294Rop7Y5Mn7kVS-node_ljPC7bL85VsDR5GM\",\"selected\":false},{\"markerEnd\":{\"type\":\"arrowclosed\",\"width\":20,\"height\":20},\"source\":\"node_ljPC7bL85VsDR5GM\",\"target\":\"node_6NkeJWpoAiVEeSfT\",\"id\":\"xy-edge__node_ljPC7bL85VsDR5GM-node_6NkeJWpoAiVEeSfT\",\"selected\":false},{\"markerEnd\":{\"type\":\"arrowclosed\",\"width\":20,\"height\":20},\"source\":\"node_6NkeJWpoAiVEeSfT\",\"target\":\"node_Mu2UKDuvV3bKp8lL\",\"id\":\"xy-edge__node_6NkeJWpoAiVEeSfT-node_Mu2UKDuvV3bKp8lL\",\"selected\":false},{\"markerEnd\":{\"type\":\"arrowclosed\",\"width\":20,\"height\":20},\"source\":\"node_Mu2UKDuvV3bKp8lL\",\"target\":\"node_CzPf0au4aE3naghj\",\"id\":\"xy-edge__node_Mu2UKDuvV3bKp8lL-node_CzPf0au4aE3naghj\"}],\"viewport\":{\"x\":250,\"y\":100,\"zoom\":1}}');

SET FOREIGN_KEY_CHECKS = 1;
